[package]
name = "pea"
version = "0.0.1"
edition = "2021"
authors = [ "Jorge Harrisonn <j.h.m.t.v.10@gmail.com>" ]
description = "Page 'em All, a CLI to page the output of your commands"
license-file = "LICENSE"

[dependencies]
